app:
  name: college-app

replicaCount: 2

image:
  repository: kajapathyk/duniversity-college-portal
  tag: latest

ports:
  containerPort: 3000

mysql:
  replicaCount: 1
  image:
    repository: mariadb
    tag: 10.5
  ports:
    containerPort: 3306
  storage:
    size: 1Gi
    storageClassName: nfs-csi-storage

