apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: gateway-ns
spec:
  replicas: {{ .Values.replicaCount}}


  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: college-app

  template:
    metadata:
      labels:
        app: college-app
    spec:
      containers:
        - name: college-app
          image: "{{ .Values.image.repository }}: {{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.ports.containerPort }}


          envFrom:
            - configMapRef:
                name: college-config
            - secretRef:
                name: college-secret

          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: college-service
  namespace: gateway-ns
spec:
  selector:
    app: college-app
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP