apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: college-mysql-pvc
  namespace: gateway-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi-storage